name: VIDEO SNIPER PRO
title: VIDEO SNIPER PRO

highlighter: rouge

exclude: 
  - node_modules
  - gulpfile.js
  - package.json
  - .editorconfig
  - .gitignore
  - "package-lock.json"

about: 

plugins:
  - jekyll-inline-svg
